"""add priority level to tickets

Revision ID: 854903b64d13
Revises: d166d0554fed
Create Date: 2026-03-26 19:11:50.412660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854903b64d13'
down_revision = 'd166d0554fed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('priority_level')

    # ### end Alembic commands ###
